apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-web-delayed
  name: app-web-delayed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-web-delayed
  template:
    metadata:
      labels:
        app: app-web-delayed
    spec:
      containers:
      - image: ghcr.io/wiktorvip/app-web-delayed:v1
        name: app-web-delayed
        ports:
        - containerPort: 9000
        env:
        - name: APP_START_DELAY
          value: "60"
        readinessProbe:
          httpGet:
            path: /live
            port: 9000
          initialDelaySeconds: 55
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /live
            port: 9000
          initialDelaySeconds: 60
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: app-web-delayed
  labels:
    app: app-web-delayed
spec:
  selector:
    app: app-web-delayed
  type: NodePort
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    nodePort: 30222

