apiVersion: v1
kind: Pod
metadata:
  name: app-web-delayed
  labels:
    app: app-web-delayed
spec:
  containers:
  - name: app-web-delayed
    image: ghcr.io/wiktorvip/app-web-delayed
    imagePullPolicy: Always
    ports:
    - containerPort: 9000
    env:
    - name: APP_START_DELAY
      value: "60"
---
apiVersion: v1
kind: Service
metadata:
  name: app-web-delayed
  labels:
    app: app-web-delayed
spec:
  selector:
    app: app-web-delayed
  type: NodePort
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    nodePort: 30222
