apiVersion: v1
kind: Pod
metadata:
  name: app-web-delayed
  labels:
    app: app-web-delayed
spec:
  containers:
  - name: app-web-delayed
    image: ghcr.io/wiktorvip/app-web-delayed
    imagePullPolicy: Always
    ports:
    - containerPort: 9000
    env:
    - name: APP_START_DELAY
      value: "60"
